### ISSUE TITLE
如何爬取一个用户所有作品

### ISSUE THREAD

**Issue by GodeCAt** [Superheroff/dyapitest#2]
现在只允许爬取一页视频，有没有什么方法能够爬取所有视频呢？

**Comment by Superheroff** [comment]
登录或者知道对方一个作品id的情况下可以

**Comment by GodeCAt** [comment]
能够问一下应该怎么做吗

**Comment by GodeCAt** [comment]
> 登录或者知道对方一个作品id的情况下可以

已经可以知道对方一个作品id

**Comment by Superheroff** [comment]
> > 登录或者知道对方一个作品id的情况下可以
> 
> 已经可以知道对方一个作品id

url路径改成`/aweme/v1/web/locate/post/`并且传入`locate_item_id`这个参数

**Comment by GodeCAt** [comment]
能够问一下应该怎么做吗不需要其他参数了吗

**Comment by Superheroff** [comment]
> 能够问一下应该怎么做吗不需要其他参数了吗

其他不变

**Comment by GodeCAt** [comment]
请问url具体在哪修改呢，完整url是怎样的，参数是从header传进去吗，还是从url里传进去呢。
![image](https://user-images.githubusercontent.com/98507651/233879336-cf9daedb-21d4-4411-b9c3-ba8c783bc399.png)
这是我自己做的失败尝试

**Comment by Superheroff** [comment]
> 请问url具体在哪修改呢，完整url是怎样的，参数是从header传进去吗，还是从url里传进去呢。
> 
> ![image](https://user-images.githubusercontent.com/98507651/233879336-cf9daedb-21d4-4411-b9c3-ba8c783bc399.png)
> 
> 这是我自己做的失败尝试
> 
> 

- 方法告诉你了需要你自己完成，我不提供demo，你图片中的代码只适用于取一页的作品

**Comment by GodeCAt** [comment]
好的，谢谢博主
